FUNCTION ZFC_SUWON_215_SFLIGHT.
*"----------------------------------------------------------------------
*"*"Local Interface:
*"  IMPORTING
*"     REFERENCE(IS_SFLIGHT) TYPE  SFLIGHT OPTIONAL
*"     REFERENCE(IV_CHAR) TYPE  C OPTIONAL
*"  EXPORTING
*"     REFERENCE(ES_SFLIGHT) TYPE  SFLIGHT
*"  TABLES
*"      T_SFLIGHT STRUCTURE  SFLIGHT OPTIONAL
*"  CHANGING
*"     REFERENCE(CS_SFLIGHT) TYPE  SFLIGHT OPTIONAL
*"----------------------------------------------------------------------
  IF IV_CHAR IS NOT INITIAL.
    SELECT CARRID CONNID
      INTO CORRESPONDING FIELDS OF TABLE T_SFLIGHT
      FROM SFLIGHT
      WHERE CARRID = IS_SFLIGHT-CARRID.
  ELSE.
    IF IS_SFLIGHT IS NOT INITIAL.
      SELECT SINGLE CARRID CONNID
        INTO CORRESPONDING FIELDS OF ES_SFLIGHT
        FROM SFLIGHT
        WHERE CARRID = IS_SFLIGHT-CARRID.

    ELSEIF CS_SFLIGHT IS NOT INITIAL.
      SELECT SINGLE CARRID CONNID
        INTO CORRESPONDING FIELDS OF CS_SFLIGHT
        FROM SFLIGHT
        WHERE CARRID = CS_SFLIGHT-CARRID.
    ENDIF.
  ENDIF.




ENDFUNCTION.
