*&---------------------------------------------------------------------*
*& Report ZRTEST_215_07
*&---------------------------------------------------------------------*
*&
*&---------------------------------------------------------------------*
REPORT ZRTEST_215_07.

"DATA 선언

"조회조건

"INITIALIZAION

"AT SELECTION-SCRENN

"START-OF-SELECTION

"END-OF-SELCTION

"""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""

*DATA : BEGIN OF GT_DATA OCCURS 0,
*        ZCODE LIKE ZTTEST_215_HR-ZCODE,
*        ZNAME LIKE ZTTEST_215_HR-ZNAME,
*       END OF GT_DATA.
*
*PARAMETERS : P_ZCODE1 TYPE ZTTEST_215_HR-ZCODE OBLIGATORY.
*
*INITIALIZATION.
*
*"AT SELECTION-SCREEN
*
*START-OF-SELECTION. "SELECT
*  SELECT ZCODE ZNAME
*    INTO TABLE GT_DATA
*    FROM ZTTEST_215_HR
*    WHERE ZCODE = P_ZCODE1.
*
*END-OF-SELECTION.
*  LOOP AT GT_DATA.
*    WRITE : / GT_DATA.
*  ENDLOOP.

"""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""
"버튼버튼버튼버튼버튼버튼버튼버튼
TABLES : ZTTEST_215_HR, SSCRFIELDS.
*TABLES : ZTTEST_215_HR.

"버튼버튼버튼버튼버튼버튼버튼버튼
DATA : G_FUNCTION_KEY LIKE SMP_DYNTXT.

"버튼버튼버튼버튼버튼버튼버튼버튼
SELECTION-SCREEN : FUNCTION KEY 1,
                   FUNCTION KEY 2,
                   FUNCTION KEY 3,
                   FUNCTION KEY 4,
                   FUNCTION KEY 5.

DATA : BEGIN OF GT_DATA OCCURS 0,
        ZCODE LIKE ZTTEST_215_HR-ZCODE,
        ZNAME LIKE ZTTEST_215_HR-ZNAME,
       END OF GT_DATA.

"BLOCK1
SELECTION-SCREEN BEGIN OF BLOCK BLOCK1 WITH FRAME TITLE TEXT-B01.
"조회조건

PARAMETERS : P_ZCODE1 TYPE ZTTEST_215_HR-ZCODE. "코드1
PARAMETERS : P_ZCODE2 TYPE ZTTEST_215_HR-ZCODE. "코드2
SELECT-OPTIONS : S_ZCODE2 FOR ZTTEST_215_HR-ZCODE.

SELECTION-SCREEN SKIP 1.

"BLOCK2
SELECTION-SCREEN BEGIN OF BLOCK BLOCK2 WITH FRAME TITLE TEXT-B02.
"라디오버튼

SELECTION-SCREEN BEGIN OF LINE.

SELECTION-SCREEN POSITION 1.
SELECTION-SCREEN COMMENT (10) TEXT-S01. "라디오 조건 :

SELECTION-SCREEN POSITION 15.
PARAMETERS : RA_01 RADIOBUTTON GROUP GR1 DEFAULT 'X' USER-COMMAND UCOMM1. "나중에
SELECTION-SCREEN COMMENT (10) TEXT-S02 FOR FIELD RA_01. "라디오1

SELECTION-SCREEN POSITION 30.
PARAMETERS : RA_02 RADIOBUTTON GROUP GR1.
SELECTION-SCREEN COMMENT (10) TEXT-S03 FOR FIELD RA_02. "라디오2

SELECTION-SCREEN END OF LINE.

SELECTION-SCREEN END OF BLOCK BLOCK2.

SELECTION-SCREEN SKIP 1.

PARAMETERS : P_ZCODE3 TYPE ZTTEST_215_HR-ZCODE.

PARAMETERS : P_ZCODE4 TYPE ZTTEST_215_HR-ZCODE MODIF ID MO1. "그룹 "나중에
PARAMETERS : P_ZCODE5 TYPE ZTTEST_215_HR-ZCODE MODIF ID MO1. "그룹 "나중에


SELECTION-SCREEN END OF BLOCK BLOCK1.

INITIALIZATION.
  P_ZCODE1 = '002'.

  S_ZCODE2-SIGN = 'I'.
  S_ZCODE2-OPTION = 'EQ'.
  S_ZCODE2-LOW = '001'.
  APPEND S_ZCODE2.

  CLEAR : S_ZCODE2, S_ZCODE2[].
  S_ZCODE2-SIGN = 'I'.
  S_ZCODE2-OPTION = 'BT'.
  S_ZCODE2-LOW = '002'.
  S_ZCODE2-HIGH = '004'.
  APPEND S_ZCODE2.

  SY-TITLE = '215'.

  "버튼버튼버튼버튼버튼버튼버튼버튼
  G_FUNCTION_KEY-ICON_ID = ICON_IMPORT.
  G_FUNCTION_KEY-ICON_TEXT = '버튼 TEST'.
  SSCRFIELDS-FUNCTXT_01 = G_FUNCTION_KEY.

  G_FUNCTION_KEY-ICON_ID = ICON_IMPORT.
  G_FUNCTION_KEY-ICON_TEXT = '1111 TEST'.
  SSCRFIELDS-FUNCTXT_02 = G_FUNCTION_KEY.

"버튼버튼버튼버튼버튼버튼버튼버튼
AT SELECTION-SCREEN.
  CASE SSCRFIELDS-UCOMM.
    WHEN 'FC01'.
      MESSAGE '버튼 TEST!!' TYPE 'I'.
  ENDCASE.

AT SELECTION-SCREEN ON P_ZCODE1.
  IF P_ZCODE1 <> '002'.
*    MESSAGE 'ONLY 002!' TYPE 'S' DISPLAY LIKE 'E'.
*    MESSAGE 'ONLY 002!' TYPE 'I'.
*    MESSAGE 'ONLY 002!' TYPE 'W'.
*    MESSAGE 'ONLY 002!' TYPE 'E'.
    MESSAGE 'ONLY 002!' TYPE 'S' DISPLAY LIKE 'E'.
  ENDIF.

AT SELECTION-SCREEN ON BLOCK BLOCK1.
  IF P_ZCODE3 = '001' AND P_ZCODE4 = '002' AND P_ZCODE5 = '003'.
  ELSE.
    MESSAGE 'P_ZCODE3~5 값 1,2,3 입력!!' TYPE 'S' DISPLAY LIKE 'E'.
  ENDIF.

AT SELECTION-SCREEN ON HELP-REQUEST FOR S_ZCODE2.
  MESSAGE 'TABLE : ZTTEST_215_HR 참고!' TYPE 'I'.

AT SELECTION-SCREEN OUTPUT.
  LOOP AT SCREEN.
    IF RA_01 IS NOT INITIAL.
      IF SCREEN-NAME = 'P_ZCODE1'.
        SCREEN-INPUT = 0.
      ENDIF.

    ELSEIF RA_02 IS NOT INITIAL.
      IF SCREEN-NAME = 'P_ZCODE2'.
        SCREEN-INPUT = 0.
        SCREEN-INVISIBLE = 1.
*        SCREEN-ACTIVE = 0.
      ENDIF.
    ENDIF.

    IF SCREEN-NAME = 'P_ZCODE3'.
*      SCREEN-REQUIRED = 1.
    ENDIF.

    IF SCREEN-GROUP1 = 'MO1'.
*      SCREEN-INPUT = 0.
      SCREEN-INTENSIFIED = 1.
    ENDIF.

    MODIFY SCREEN.
  ENDLOOP.

START-OF-SELECTION. "SELECT
  SELECT ZCODE ZNAME
    INTO TABLE GT_DATA
    FROM ZTTEST_215_HR
    WHERE ZCODE = P_ZCODE1.

  SELECT ZCODE ZNAME
    APPENDING TABLE GT_DATA
    FROM ZTTEST_215_HR
    WHERE ZCODE IN S_ZCODE2.

END-OF-SELECTION.
  LOOP AT GT_DATA.
    WRITE : / GT_DATA.
  ENDLOOP.
