*&---------------------------------------------------------------------*
*& Include          ZRTEST_215_14_TOP
*&---------------------------------------------------------------------*

TABLES : ZTTEST_215_HR.

DATA : BEGIN OF GT_DATA OCCURS 0,
        ICON(4), "DATA CHANGED TEST
        ZCODE LIKE ZTTEST_215_HR-ZCODE,
        ZNAME LIKE ZTTEST_215_HR-ZNAME,
        CHECK,
        INT TYPE I,
        NAME(10), "DATA CHANGED TEST
        OK_NO(2), "DATA_CHANGED FINISHED

        INFO(4), "INFO_FNAME
        CTAB TYPE LVC_T_SCOL, "CTAB_FNAME
        STYLE TYPE LVC_T_STYL, "STYLEFNAME
       END OF GT_DATA.

DATA : OK_CODE TYPE SY-UCOMM.

DATA : GC_DOCKING TYPE REF TO CL_GUI_DOCKING_CONTAINER.
DATA : GC_SPLITTER TYPE REF TO CL_GUI_SPLITTER_CONTAINER.
DATA : GC_CONTAINER_1 TYPE REF TO CL_GUI_CONTAINER.
DATA : GC_CONTAINER_2 TYPE REF TO CL_GUI_CONTAINER.
DATA : GC_GRID_1 TYPE REF TO CL_GUI_ALV_GRID.
DATA : GC_GRID_2 TYPE REF TO CL_GUI_ALV_GRID.
DATA : GT_FCAT TYPE LVC_T_FCAT.
DATA : GS_FCAT TYPE LVC_S_FCAT.

DATA : GT_FCAT_2 TYPE LVC_T_FCAT.
DATA : GS_FCAT_2 TYPE LVC_S_FCAT.

DATA : GS_SORT TYPE LVC_S_SORT.
DATA : GT_SORT TYPE LVC_T_SORT.

DATA : GS_VARIANT TYPE DISVARIANT.

DATA : GT_TOOLBAR TYPE UI_FUNCTIONS.

DATA : GS_LAYOUT TYPE LVC_S_LAYO.

DATA : GC_EVENT TYPE REF TO CLASS_EVENT.
