*&---------------------------------------------------------------------*
*& Include          ZRTEST_215_TEMP02_TOP
*&---------------------------------------------------------------------*

TABLES : MARA.

DATA : BEGIN OF GS_DATA,
        ICON(4),
        MATNR LIKE MARA-MATNR,
        MAKTX LIKE MAKT-MAKTX,
        INT TYPE I,
        CHAR(100),
        CHAR2(100),
       END OF GS_DATA.

DATA : GT_DATA LIKE TABLE OF GS_DATA.

DATA : OK_CODE TYPE SY-UCOMM.

DATA : GC_DOCKING TYPE REF TO CL_GUI_DOCKING_CONTAINER.

DATA : GC_GRID TYPE REF TO CL_GUI_ALV_GRID.

DATA : GC_SPLITTER TYPE REF TO CL_GUI_SPLITTER_CONTAINER.

DATA : GC_CONTAINER_1 TYPE REF TO CL_GUI_CONTAINER.
DATA : GC_CONTAINER_2 TYPE REF TO CL_GUI_CONTAINER.

DATA : GC_GRID_1 TYPE REF TO CL_GUI_ALV_GRID.
DATA : GC_GRID_2 TYPE REF TO CL_GUI_ALV_GRID.


DATA : GT_FCAT TYPE LVC_T_FCAT.
DATA : GS_FCAT TYPE LVC_S_FCAT.

DATA : GO_EVENT TYPE REF TO EVENT.
