*&---------------------------------------------------------------------*
*& Report ZRTEST_215_06
*&---------------------------------------------------------------------*
*&
*&---------------------------------------------------------------------*
REPORT ZRTEST_215_06.

TABLES : ZTTEST_215_HR, ZTTEST_215_UNI.

PARAMETERS : P_ZCODE TYPE ZTTEST_215_HR-ZCODE.

WRITE : / P_ZCODE.

PARAMETERS : P_1 TYPE C LENGTH 1 DEFAULT 'A',
             P_2 TYPE CHAR1 DEFAULT 'A',
             P_3 TYPE C DEFAULT 'A',
             P_4(1) DEFAULT 'A',
             P_5 DEFAULT 'A'.

PARAMETERS : P_6 TYPE P DECIMALS 2 DEFAULT '123.45'.

*PARAMETERS : P_7 LIKE ZTTEST_215_HR-ZCODE.
PARAMETERS : P_7 TYPE ZTTEST_215_HR-ZCODE.

PARAMETERS : P_8 TYPE ZTTEST_215_UNI-ZMAJOR MATCHCODE OBJECT ZSHTEST_215_MAJOR_02.

PARAMETERS : P_15 TYPE ZTTEST_215_UNI-ZMAJOR AS LISTBOX VISIBLE LENGTH 10.

PARAMETERS : P_9 MODIF ID GR1.

PARAMETERS : P_10 NO-DISPLAY.

PARAMETERS : P_11 OBLIGATORY.

PARAMETERS : P_12 AS CHECKBOX.

PARAMETERS : P_13 RADIOBUTTON GROUP R1,
             P_14 RADIOBUTTON GROUP R1.

SELECTION-SCREEN SKIP 3.

SELECT-OPTIONS : S_1 FOR ZTTEST_215_HR-ZCODE DEFAULT '123'.

SELECT-OPTIONS : S_2 FOR ZTTEST_215_UNI-ZMAJOR MATCHCODE OBJECT ZSHTEST_215_MAJOR_02.

SELECT-OPTIONS : S_3 FOR ZTTEST_215_HR-ZCODE NO-DISPLAY.

SELECT-OPTIONS : S_4 FOR ZTTEST_215_HR-ZCODE OBLIGATORY.

SELECT-OPTIONS : S_5 FOR ZTTEST_215_HR-ZCODE.

SELECT-OPTIONS : S_6 FOR ZTTEST_215_HR-ZCODE NO-EXTENSION.

SELECT-OPTIONS : S_7 FOR ZTTEST_215_HR-ZCODE NO INTERVALS.

SELECT-OPTIONS : S_8 FOR ZTTEST_215_HR-ZCODE NO-EXTENSION NO INTERVALS.

"""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""
"LINE
PARAMETERS : P_CH1 AS CHECKBOX, "체크박스1
             P_CH2 AS CHECKBOX, "체크박스2
             P_CH3 AS CHECKBOX. "체크박스3

SELECTION-SCREEN BEGIN OF LINE.

"옆으로
PARAMETERS : P_CH4 AS CHECKBOX.
SELECTION-SCREEN COMMENT (10) TEXT-S01 FOR FIELD P_CH4.
"체크박스4

PARAMETERS : P_CH5 AS CHECKBOX.
SELECTION-SCREEN COMMENT (10) TEXT-S02 FOR FIELD P_CH5.
"체크박스5

PARAMETERS : P_CH6 AS CHECKBOX.
SELECTION-SCREEN COMMENT (10) TEXT-S03 FOR FIELD P_CH6.
"체크박스6

SELECTION-SCREEN END OF LINE.

"설정조건 텍스트 추가
SELECTION-SCREEN BEGIN OF LINE.
SELECTION-SCREEN COMMENT (10) TEXT-S04. "설정조건

PARAMETERS : P_CH7 AS CHECKBOX.
SELECTION-SCREEN COMMENT (10) TEXT-S01 FOR FIELD P_CH7.

PARAMETERS : P_CH8 AS CHECKBOX.
SELECTION-SCREEN COMMENT (10) TEXT-S02 FOR FIELD P_CH8.

PARAMETERS : P_CH9 AS CHECKBOX.
SELECTION-SCREEN COMMENT (10) TEXT-S03 FOR FIELD P_CH9.

SELECTION-SCREEN END OF LINE.

"텍스트와 체크박스 위치 바꿈
SELECTION-SCREEN BEGIN OF LINE.
SELECTION-SCREEN COMMENT (10) TEXT-S04.

SELECTION-SCREEN COMMENT (5) TEXT-S01 FOR FIELD P_CH10.
PARAMETERS : P_CH10 AS CHECKBOX.

SELECTION-SCREEN COMMENT (5) TEXT-S02 FOR FIELD P_CH11.
PARAMETERS : P_CH11 AS CHECKBOX.

SELECTION-SCREEN COMMENT (5) TEXT-S03 FOR FIELD P_CH12.
PARAMETERS : P_CH12 AS CHECKBOX.

SELECTION-SCREEN END OF LINE.

"POSITION
SELECTION-SCREEN BEGIN OF LINE.
SELECTION-SCREEN POSITION 1.
SELECTION-SCREEN COMMENT (10) TEXT-S04.

SELECTION-SCREEN POSITION 15.
SELECTION-SCREEN COMMENT (5) TEXT-S01 FOR FIELD P_CH13.
PARAMETERS : P_CH13 AS CHECKBOX.

SELECTION-SCREEN POSITION 25.
SELECTION-SCREEN COMMENT (5) TEXT-S02 FOR FIELD P_CH14.
PARAMETERS : P_CH14 AS CHECKBOX.

SELECTION-SCREEN POSITION 35.
SELECTION-SCREEN COMMENT (5) TEXT-S03 FOR FIELD P_CH15.
PARAMETERS : P_CH15 AS CHECKBOX.

SELECTION-SCREEN END OF LINE.

SELECTION-SCREEN SKIP 1.

"완성본 + DEFAULT
SELECTION-SCREEN BEGIN OF LINE.
SELECTION-SCREEN POSITION 1.
SELECTION-SCREEN COMMENT (10) TEXT-S04.

SELECTION-SCREEN POSITION 15.
*PARAMETERS : P_CH13 AS CHECKBOX DEFAULT 'X' MODIF ID M01.
PARAMETERS : P_CH16 AS CHECKBOX DEFAULT 'X'.
SELECTION-SCREEN COMMENT (5) TEXT-S01 FOR FIELD P_CH16.

SELECTION-SCREEN POSITION 25.
PARAMETERS : P_CH17 AS CHECKBOX.
SELECTION-SCREEN COMMENT (5) TEXT-S02 FOR FIELD P_CH17.

SELECTION-SCREEN POSITION 35.
PARAMETERS : P_CH18 AS CHECKBOX.
SELECTION-SCREEN COMMENT (5) TEXT-S03 FOR FIELD P_CH18.

SELECTION-SCREEN END OF LINE.

SELECTION-SCREEN SKIP 1.

"라디오 버튼
PARAMETERS : RA_01 RADIOBUTTON GROUP GR2,
             RA_02 RADIOBUTTON GROUP GR2.

SELECTION-SCREEN BEGIN OF LINE.

SELECTION-SCREEN POSITION 1.
SELECTION-SCREEN COMMENT (10) TEXT-S05. "조건설정

SELECTION-SCREEN POSITION 20.
PARAMETERS : RA_03 RADIOBUTTON GROUP GR3.
SELECTION-SCREEN COMMENT (10) TEXT-S06 FOR FIELD RA_03. "조건1

SELECTION-SCREEN POSITION 40.
PARAMETERS : RA_04 RADIOBUTTON GROUP GR3.
SELECTION-SCREEN COMMENT (10) TEXT-S07 FOR FIELD RA_04. "조건2

SELECTION-SCREEN END OF LINE.

""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""

SELECTION-SCREEN SKIP 1.

*TABLES : ZTTEST_215_HR.

PARAMETERS : P_ZCODE2 TYPE ZTTEST_215_HR-ZCODE. "코드번호
SELECT-OPTIONS : S_ZCODE2 FOR ZTTEST_215_HR-ZCODE. "코드번호2

SELECTION-SCREEN SKIP 2.

"BLOCK
SELECTION-SCREEN BEGIN OF BLOCK BLOCK2 WITH FRAME TITLE TEXT-B02.
"조회조건

PARAMETERS : P_ZCODE3 TYPE ZTTEST_215_HR-ZCODE.
SELECT-OPTIONS : S_ZCODE3 FOR ZTTEST_215_HR-ZCODE.

SELECTION-SCREEN END OF BLOCK BLOCK2.

"BLOCK + LINE
SELECTION-SCREEN BEGIN OF BLOCK BLOCK3 WITH FRAME TITLE TEXT-B03.
"박스!

SELECTION-SCREEN BEGIN OF LINE.

SELECTION-SCREEN POSITION 1.
SELECTION-SCREEN COMMENT (10) TEXT-S08. "TEST

SELECTION-SCREEN POSITION 20.
SELECTION-SCREEN COMMENT (10) TEXT-S09 FOR FIELD P_ZCODE4. "코드번호
PARAMETERS : P_ZCODE4 TYPE ZTTEST_215_HR-ZCODE.

SELECTION-SCREEN POSITION 40.
SELECTION-SCREEN COMMENT (10) TEXT-S09 FOR FIELD P_ZCODE5.
PARAMETERS : P_ZCODE5 TYPE ZTTEST_215_HR-ZCODE.

SELECTION-SCREEN END OF LINE.

SELECTION-SCREEN END OF BLOCK BLOCK3.

SELECTION-SCREEN SKIP 1.

"완성본
SELECTION-SCREEN BEGIN OF BLOCK BLOCK4 WITH FRAME TITLE TEXT-B03.
"박스!

"PARAMETERS
SELECTION-SCREEN BEGIN OF LINE.

SELECTION-SCREEN POSITION 1.
SELECTION-SCREEN COMMENT (10) TEXT-S08. "TEST

SELECTION-SCREEN POSITION 20.
SELECTION-SCREEN COMMENT (10) TEXT-S09 FOR FIELD P_ZCODE6. "코드번호
PARAMETERS : P_ZCODE6 TYPE ZTTEST_215_HR-ZCODE.

SELECTION-SCREEN POSITION 40.
SELECTION-SCREEN COMMENT (10) TEXT-S09 FOR FIELD P_ZCODE7.
PARAMETERS : P_ZCODE7 TYPE ZTTEST_215_HR-ZCODE.

SELECTION-SCREEN END OF LINE.

SELECTION-SCREEN SKIP 1.

"CHECKBOX
SELECTION-SCREEN BEGIN OF LINE.
SELECTION-SCREEN POSITION 1.
SELECTION-SCREEN COMMENT (10) TEXT-S10. "체크박스

SELECTION-SCREEN POSITION 20.
PARAMETERS : P_CH19 AS CHECKBOX DEFAULT 'X'.
SELECTION-SCREEN COMMENT (10) TEXT-S11 FOR FIELD P_CH19. "체크1

SELECTION-SCREEN POSITION 40.
PARAMETERS : P_CH20 AS CHECKBOX.
SELECTION-SCREEN COMMENT (10) TEXT-S12 FOR FIELD P_CH20. "체크2

SELECTION-SCREEN END OF LINE.

SELECTION-SCREEN SKIP 1.

"RADIO BUTTON
SELECTION-SCREEN BEGIN OF LINE.
SELECTION-SCREEN POSITION 1.
SELECTION-SCREEN COMMENT (10) TEXT-S13. "라디오버튼

SELECTION-SCREEN POSITION 20.
PARAMETERS : RA_05 RADIOBUTTON GROUP GR4.
SELECTION-SCREEN COMMENT (10) TEXT-S14 FOR FIELD RA_05. "라디오1

SELECTION-SCREEN POSITION 40.
PARAMETERS : RA_06 RADIOBUTTON GROUP GR4.
SELECTION-SCREEN COMMENT (10) TEXT-S15 FOR FIELD RA_06. "라디오2

SELECTION-SCREEN END OF LINE.

SELECTION-SCREEN END OF BLOCK BLOCK4.
