*&---------------------------------------------------------------------*
*& Report ZRTEST_215_05
*&---------------------------------------------------------------------*
*&
*&---------------------------------------------------------------------*
REPORT ZRTEST_215_05.

DATA : GT_ZTTEST_215_HR_01 LIKE ZTTEST_215_HR OCCURS 0." WITH HEADER LINE.

SELECT *
  INTO TABLE GT_ZTTEST_215_HR_01
  FROM ZTTEST_215_HR.

*CL_DEMO_OUTPUT=>DISPLAY( GT_ZTTEST_215_HR_01 ).

DATA : GS_ZTTEST_215_HR_02 LIKE ZTTEST_215_HR.

SELECT SINGLE *
  INTO GS_ZTTEST_215_HR_02
  FROM ZTTEST_215_HR.

*CL_DEMO_OUTPUT=>DISPLAY( GS_ZTTEST_215_HR_02 ).

SELECT MANDT ZCODE ZNAME ZGENDER
       ZPHONE ZADDRESS ZAGE
       ZHOBBY
  INTO TABLE GT_ZTTEST_215_HR_01
  FROM ZTTEST_215_HR.

*CL_DEMO_OUTPUT=>DISPLAY( GT_ZTTEST_215_HR_01 ).

"INTO CORRESPONDING FIELDS OF
DATA : BEGIN OF GS_ZTTEST_215_HR_03,
        ZCODE LIKE ZTTEST_215_HR-ZCODE,
        ZNAME LIKE ZTTEST_215_HR-ZNAME,
        ZPHONE LIKE ZTTEST_215_HR-ZPHONE,
        ZGENDER LIKE ZTTEST_215_HR-ZGENDER,
       END OF GS_ZTTEST_215_HR_03.

DATA : GT_ZTTEST_215_HR_03 LIKE TABLE OF GS_ZTTEST_215_HR_03.

SELECT ZCODE ZNAME ZGENDER ZPHONE
  INTO TABLE GT_ZTTEST_215_HR_03
  FROM ZTTEST_215_HR.

*CL_DEMO_OUTPUT=>DISPLAY( GT_ZTTEST_215_HR_03 ).

SELECT ZCODE ZNAME ZGENDER ZPHONE
  INTO CORRESPONDING FIELDS OF TABLE GT_ZTTEST_215_HR_03
  FROM ZTTEST_215_HR.

*CL_DEMO_OUTPUT=>DISPLAY( GT_ZTTEST_215_HR_03 ).

"WHERE
SELECT *
  INTO CORRESPONDING FIELDS OF TABLE GT_ZTTEST_215_HR_03
  FROM ZTTEST_215_HR
  WHERE ZCODE = '001'.

*CL_DEMO_OUTPUT=>DISPLAY( GT_ZTTEST_215_HR_03 ).

"SELECT SINGLE + CORRESPONDING
DATA : BEGIN OF GS_ZTTEST_215_HR_04,
        ZCODE LIKE ZTTEST_215_HR-ZCODE,
        ZNAME LIKE ZTTEST_215_HR-ZNAME,
        ZPHONE LIKE ZTTEST_215_HR-ZPHONE,
        ZGENDER LIKE ZTTEST_215_HR-ZGENDER,
       END OF GS_ZTTEST_215_HR_04.

SELECT SINGLE ZCODE ZNAME ZGENDER ZPHONE
  INTO GS_ZTTEST_215_HR_04
  FROM ZTTEST_215_HR
  WHERE ZCODE = '002'.

*CL_DEMO_OUTPUT=>DISPLAY( GS_ZTTEST_215_HR_04 ).

SELECT SINGLE ZCODE ZNAME ZGENDER ZPHONE
  INTO CORRESPONDING FIELDS OF GS_ZTTEST_215_HR_04
  FROM ZTTEST_215_HR
  WHERE ZCODE = '002'.

DATA : LV_ZCODE LIKE ZTTEST_215_HR-ZCODE.

SELECT SINGLE ZCODE
  INTO LV_ZCODE
  FROM ZTTEST_215_HR
  WHERE ZCODE = '002'.

DATA : LV_ZNAME LIKE ZTTEST_215_HR-ZNAME.

SELECT SINGLE ZCODE ZNAME
  INTO ( LV_ZCODE, LV_ZNAME )
  FROM ZTTEST_215_HR
  WHERE ZCODE = '002'.

*CL_DEMO_OUTPUT=>DISPLAY( GS_ZTTEST_215_HR_04 ).

DATA : GT_ZTTEST_215_HR_10 LIKE ZTTEST_215_HR OCCURS 0." WITH HEADER LINE.

"EQ = / NE <> / < <= / > >=
SELECT *
  INTO TABLE GT_ZTTEST_215_HR_10
  FROM ZTTEST_215_HR
  WHERE ZGENDER = '남'.

SELECT *
  INTO TABLE GT_ZTTEST_215_HR_10
  FROM ZTTEST_215_HR
  WHERE ZGENDER EQ '남'.

SELECT *
  INTO TABLE GT_ZTTEST_215_HR_10
  FROM ZTTEST_215_HR
  WHERE ZGENDER <> '남'.

SELECT *
  INTO TABLE GT_ZTTEST_215_HR_10
  FROM ZTTEST_215_HR
  WHERE ZGENDER NE '남'.

SELECT *
  INTO TABLE GT_ZTTEST_215_HR_10
  FROM ZTTEST_215_HR
  WHERE ZAGE > 23. "GT

SELECT *
  INTO TABLE GT_ZTTEST_215_HR_10
  FROM ZTTEST_215_HR
  WHERE ZAGE >= 23. "GE

SELECT *
  INTO TABLE GT_ZTTEST_215_HR_10
  FROM ZTTEST_215_HR
  WHERE ZAGE < 23. "LT

SELECT *
  INTO TABLE GT_ZTTEST_215_HR_10
  FROM ZTTEST_215_HR
  WHERE ZAGE <= 23. "LE

SELECT *
  INTO TABLE GT_ZTTEST_215_HR_10
  FROM ZTTEST_215_HR
  WHERE ZAGE BETWEEN '20' AND '23'.

SELECT *
  INTO TABLE GT_ZTTEST_215_HR_10
  FROM ZTTEST_215_HR
  WHERE ZNAME LIKE '이원%'.

SELECT *
  INTO TABLE GT_ZTTEST_215_HR_10
  FROM ZTTEST_215_HR
  WHERE ZGENDER IN ( '남', '여' )
  AND   ZHOBBY IN ( '탁구', '독서' ).

*CL_DEMO_OUTPUT=>DISPLAY( GT_ZTTEST_215_HR_10 ).

"RANGES
RANGES : GR_ZCODE FOR ZTTEST_215_HR-ZCODE.

GR_ZCODE-SIGN = 'I'.
GR_ZCODE-OPTION = 'EQ'.
GR_ZCODE-LOW = '001'.
APPEND GR_ZCODE.

GR_ZCODE-SIGN = 'I'.
GR_ZCODE-OPTION = 'EQ'.
GR_ZCODE-LOW = '003'.
APPEND GR_ZCODE.

DATA : BEGIN OF GS_ZTTEST_215_HR_11,
        ZCODE LIKE ZTTEST_215_HR-ZCODE,
        ZNAME LIKE ZTTEST_215_HR-ZNAME,
       END OF GS_ZTTEST_215_HR_11.

DATA : GT_ZTTEST_215_HR_11 LIKE TABLE OF GS_ZTTEST_215_HR_11.

SELECT ZCODE ZNAME
  INTO TABLE GT_ZTTEST_215_HR_11
  FROM ZTTEST_215_HR
  WHERE ZCODE IN GR_ZCODE.

*CL_DEMO_OUTPUT=>DISPLAY( GT_ZTTEST_215_HR_11 ).

CLEAR : GR_ZCODE, GR_ZCODE[].

GR_ZCODE-SIGN = 'I'.
GR_ZCODE-OPTION = 'BT'.
GR_ZCODE-LOW = '002'.
GR_ZCODE-HIGH = '004'.
APPEND GR_ZCODE.

SELECT ZCODE ZNAME
  INTO TABLE GT_ZTTEST_215_HR_11
  FROM ZTTEST_215_HR
  WHERE ZCODE IN GR_ZCODE.

*CL_DEMO_OUTPUT=>DISPLAY( GT_ZTTEST_215_HR_11 ).

"JOIN 실습!! JOIN 실습!! JOIN 실습!! JOIN 실습!!
DATA : BEGIN OF GS_ZTTEST_215_HR_UNI_05,
        ZCODE LIKE ZTTEST_215_HR-ZCODE,
        ZNAME LIKE ZTTEST_215_HR-ZNAME,
        ZAGE LIKE ZTTEST_215_HR-ZAGE,

        ZMAJOR LIKE ZTTEST_215_UNI-ZMAJOR,
        ZLEVEL LIKE ZTTEST_215_UNI-ZLEVEL,
       END OF GS_ZTTEST_215_HR_UNI_05.

DATA : GT_ZTTEST_215_HR_UNI_05 LIKE TABLE OF GS_ZTTEST_215_HR_UNI_05.

DATA : BEGIN OF GS_ZTTEST_215_HR_06,
        ZCODE LIKE ZTTEST_215_HR-ZCODE,
        ZNAME LIKE ZTTEST_215_HR-ZNAME,
        ZAGE LIKE ZTTEST_215_HR-ZAGE,
       END OF GS_ZTTEST_215_HR_06.

DATA : GT_ZTTEST_215_HR_06 LIKE TABLE OF GS_ZTTEST_215_HR_06.

DATA : BEGIN OF GS_ZTTEST_215_UNI_07,
        ZCODE LIKE ZTTEST_215_UNI-ZCODE,
        ZMAJOR LIKE ZTTEST_215_UNI-ZMAJOR,
        ZLEVEL LIKE ZTTEST_215_UNI-ZLEVEL,
       END OF GS_ZTTEST_215_UNI_07.

DATA : GT_ZTTEST_215_UNI_07 LIKE TABLE OF GS_ZTTEST_215_UNI_07.

SELECT *
  INTO CORRESPONDING FIELDS OF TABLE GT_ZTTEST_215_HR_06
  FROM ZTTEST_215_HR
  WHERE ZCODE = '002'.

*CL_DEMO_OUTPUT=>DISPLAY( GT_ZTTEST_215_HR_06 ).

SELECT *
  INTO CORRESPONDING FIELDS OF TABLE GT_ZTTEST_215_UNI_07
  FROM ZTTEST_215_UNI
  WHERE ZCODE = '002'.

*CL_DEMO_OUTPUT=>DISPLAY( GT_ZTTEST_215_UNI_07 ).


LOOP AT GT_ZTTEST_215_HR_06 INTO GS_ZTTEST_215_HR_06.
  MOVE-CORRESPONDING GS_ZTTEST_215_HR_06
  TO GS_ZTTEST_215_HR_UNI_05.

  READ TABLE GT_ZTTEST_215_UNI_07 INTO GS_ZTTEST_215_UNI_07
  WITH KEY ZCODE = GS_ZTTEST_215_HR_UNI_05-ZCODE.
  IF SY-SUBRC = 0.
    MOVE-CORRESPONDING GS_ZTTEST_215_UNI_07
    TO GS_ZTTEST_215_HR_UNI_05.
  ENDIF.

  APPEND GS_ZTTEST_215_HR_UNI_05 TO GT_ZTTEST_215_HR_UNI_05.
ENDLOOP.

SELECT ZTTEST_215_HR~ZCODE ZTTEST_215_HR~ZNAME ZTTEST_215_HR~ZAGE
       ZTTEST_215_UNI~ZMAJOR ZTTEST_215_UNI~ZLEVEL
  INTO TABLE GT_ZTTEST_215_HR_UNI_05
  FROM ZTTEST_215_HR
  INNER JOIN ZTTEST_215_UNI
  ON ZTTEST_215_HR~ZCODE = ZTTEST_215_UNI~ZCODE
  WHERE ZTTEST_215_HR~ZCODE = '002'.

SELECT A~ZCODE A~ZNAME A~ZAGE
       B~ZMAJOR B~ZLEVEL
  INTO TABLE GT_ZTTEST_215_HR_UNI_05
  FROM ZTTEST_215_HR AS A
  INNER JOIN ZTTEST_215_UNI AS B
  ON A~ZCODE = B~ZCODE
  WHERE A~ZCODE = '002'.

  "JOIN 실습!! JOIN 실습!! JOIN 실습!! JOIN 실습!!

*CL_DEMO_OUTPUT=>DISPLAY( GT_ZTTEST_215_HR_UNI_05 ).

DATA : BEGIN OF GS_ZTTEST_215_HR_UNI_COM_08,
        ZCODE LIKE ZTTEST_215_HR-ZCODE,
        ZNAME LIKE ZTTEST_215_HR-ZNAME,
        ZMAJOR LIKE ZTTEST_215_UNI-ZMAJOR,
        ZLEVEL LIKE ZTTEST_215_UNI-ZLEVEL,
        ZTOEIC LIKE ZTTEST_215_COM-ZTOEIC,
        ZFOREIGN LIKE ZTTEST_215_COM-ZFOREIGN,
       END OF GS_ZTTEST_215_HR_UNI_COM_08.

DATA : GT_ZTTEST_215_HR_UNI_COM_08 LIKE TABLE OF GS_ZTTEST_215_HR_UNI_COM_08.

SELECT A~ZCODE A~ZNAME
       B~ZMAJOR B~ZLEVEL
       C~ZTOEIC C~ZFOREIGN
  INTO TABLE GT_ZTTEST_215_HR_UNI_COM_08
  FROM ZTTEST_215_HR AS A
  INNER JOIN ZTTEST_215_UNI AS B
  ON A~ZCODE = B~ZCODE
  INNER JOIN ZTTEST_215_COM AS C
  ON A~ZCODE = C~ZCODE
  WHERE A~ZCODE IN ( '001', '002' ).

*CL_DEMO_OUTPUT=>DISPLAY( GT_ZTTEST_215_HR_UNI_COM_08 ).

"OUTER JOIN 실습!! OUTER JOIN 실습!! OUTER JOIN 실습!!
DATA : BEGIN OF GS_ZTTEST_215_HR_UNI_09,
        ZCODE LIKE ZTTEST_215_HR-ZCODE,
        ZNAME LIKE ZTTEST_215_HR-ZNAME,
        ZMAJOR LIKE ZTTEST_215_UNI-ZMAJOR,
       END OF GS_ZTTEST_215_HR_UNI_09.

DATA : GT_ZTTEST_215_HR_UNI_09 LIKE TABLE OF GS_ZTTEST_215_HR_UNI_09.

DATA : BEGIN OF GS_ZTTEST_215_HR_09_01,
        ZCODE LIKE ZTTEST_215_HR-ZCODE,
        ZNAME LIKE ZTTEST_215_HR-ZNAME,
       END OF GS_ZTTEST_215_HR_09_01.

DATA : GT_ZTTEST_215_HR_09_01 LIKE TABLE OF GS_ZTTEST_215_HR_09_01.

DATA : BEGIN OF GS_ZTTEST_215_HR_09_02,
        ZCODE LIKE ZTTEST_215_HR-ZCODE,
        ZMAJOR LIKE ZTTEST_215_UNI-ZMAJOR,
       END OF GS_ZTTEST_215_HR_09_02.

DATA : GT_ZTTEST_215_HR_09_02 LIKE TABLE OF GS_ZTTEST_215_HR_09_02.

SELECT ZCODE ZNAME
  INTO TABLE GT_ZTTEST_215_HR_09_01
  FROM ZTTEST_215_HR.

SELECT ZCODE ZMAJOR
  INTO TABLE GT_ZTTEST_215_HR_09_02
  FROM ZTTEST_215_UNI.

LOOP AT GT_ZTTEST_215_HR_09_01 INTO GS_ZTTEST_215_HR_09_01.
  MOVE-CORRESPONDING GS_ZTTEST_215_HR_09_01
  TO GS_ZTTEST_215_HR_UNI_09.

  READ TABLE GT_ZTTEST_215_HR_09_02 INTO GS_ZTTEST_215_HR_09_02
  WITH KEY ZCODE = GS_ZTTEST_215_HR_UNI_09-ZCODE.
  IF SY-SUBRC = 0.
    GS_ZTTEST_215_HR_UNI_09-ZMAJOR = GS_ZTTEST_215_HR_09_02-ZMAJOR.
  ENDIF.

  APPEND GS_ZTTEST_215_HR_UNI_09
  TO GT_ZTTEST_215_HR_UNI_09.
ENDLOOP.

SELECT A~ZCODE A~ZNAME
       B~ZMAJOR
  INTO TABLE GT_ZTTEST_215_HR_UNI_09
  FROM ZTTEST_215_HR AS A
  LEFT OUTER JOIN ZTTEST_215_UNI AS B
  ON A~ZCODE = B~ZCODE
  WHERE A~ZCODE <> SPACE.

  "OUTER JOIN 실습!! OUTER JOIN 실습!! OUTER JOIN 실습!!

*  CL_DEMO_OUTPUT=>DISPLAY( GT_ZTTEST_215_HR_UNI_09 ).

"FOR ALL ENTRIES IN 실습! FOR ALL ENTRIES IN 실습!
DATA : GT_ZTTEST_215_HR_10_01 LIKE ZTTEST_215_HR OCCURS 0.
DATA : GT_ZTTEST_215_HR_10_02 LIKE ZTTEST_215_HR OCCURS 0.
DATA : GT_ZTTEST_215_HR_10_03 LIKE ZTTEST_215_HR OCCURS 0.
DATA : GS_ZTTEST_215_HR_10_01 LIKE ZTTEST_215_HR.
DATA : GS_ZTTEST_215_HR_10_02 LIKE ZTTEST_215_HR.
DATA : GS_ZTTEST_215_HR_10_03 LIKE ZTTEST_215_HR.

SELECT *
  INTO TABLE GT_ZTTEST_215_HR_10_01
  FROM ZTTEST_215_HR
  WHERE ZGENDER = '남'
  AND   ZHOBBY = '탁구'.

SELECT *
  INTO TABLE GT_ZTTEST_215_HR_10_02
  FROM ZTTEST_215_HR
  WHERE ZGENDER = '여'
  AND   ZHOBBY = '독서'.

LOOP AT GT_ZTTEST_215_HR_10_01 INTO GS_ZTTEST_215_HR_10_01.
  MOVE GS_ZTTEST_215_HR_10_01 TO GS_ZTTEST_215_HR_10_03.

  APPEND GS_ZTTEST_215_HR_10_03 TO GT_ZTTEST_215_HR_10_03.
ENDLOOP.

LOOP AT GT_ZTTEST_215_HR_10_02 INTO GS_ZTTEST_215_HR_10_02.
  MOVE GS_ZTTEST_215_HR_10_02 TO GS_ZTTEST_215_HR_10_03.

  APPEND GS_ZTTEST_215_HR_10_03 TO GT_ZTTEST_215_HR_10_03.
ENDLOOP.

SELECT *
  INTO TABLE GT_ZTTEST_215_HR_10_03
  FROM ZTTEST_215_HR
  WHERE ZGENDER IN ( '남' )
  AND   ZHOBBY IN ( '탁구' ).

SELECT *
  APPENDING TABLE GT_ZTTEST_215_HR_10_03
  FROM ZTTEST_215_HR
  WHERE ZGENDER IN ( '여' )
  AND   ZHOBBY IN ( '독서' ).

*CL_DEMO_OUTPUT=>DISPLAY( GT_ZTTEST_215_HR_10_03 ).

DATA : BEGIN OF GS_ZTTEST_ZGENDER_ZHOBBY,
        ZGENDER LIKE ZTTEST_215_HR-ZGENDER,
        ZHOBBY LIKE ZTTEST_215_HR-ZHOBBY,
       END OF GS_ZTTEST_ZGENDER_ZHOBBY.

DATA : GT_ZTTEST_ZGENDER_ZHOBBY LIKE TABLE OF GS_ZTTEST_ZGENDER_ZHOBBY.

GS_ZTTEST_ZGENDER_ZHOBBY-ZGENDER = '남'.
GS_ZTTEST_ZGENDER_ZHOBBY-ZHOBBY = '탁구'.
APPEND GS_ZTTEST_ZGENDER_ZHOBBY TO GT_ZTTEST_ZGENDER_ZHOBBY.

GS_ZTTEST_ZGENDER_ZHOBBY-ZGENDER = '여'.
GS_ZTTEST_ZGENDER_ZHOBBY-ZHOBBY = '독서'.
APPEND GS_ZTTEST_ZGENDER_ZHOBBY TO GT_ZTTEST_ZGENDER_ZHOBBY.

SORT GT_ZTTEST_ZGENDER_ZHOBBY.
DELETE ADJACENT DUPLICATES FROM GT_ZTTEST_ZGENDER_ZHOBBY COMPARING ALL FIELDS.

IF GT_ZTTEST_ZGENDER_ZHOBBY IS NOT INITIAL.
  SELECT *
    INTO TABLE GT_ZTTEST_215_HR_10_03
    FROM ZTTEST_215_HR
    FOR ALL ENTRIES IN GT_ZTTEST_ZGENDER_ZHOBBY
    WHERE ZGENDER = GT_ZTTEST_ZGENDER_ZHOBBY-ZGENDER
    AND   ZHOBBY = GT_ZTTEST_ZGENDER_ZHOBBY-ZHOBBY.
ENDIF.
"FOR ALL ENTRIES IN 실습! FOR ALL ENTRIES IN 실습!

*CL_DEMO_OUTPUT=>DISPLAY( GT_ZTTEST_215_HR_10_03 ).

DATA : GV_ZCODE LIKE ZTTEST_215_HR-ZCODE.

"GROUP BY - 그룹별 합계를 구할 경우 사용
"HAVING - GROUP의 조건을 설정하는 WHERE
"ORDER BY - 조회된 데이터를 정렬
"DISTINCT - 중복된 값 제거

"AVG / COUNT / MAX / MIN / SUM

SELECT SINGLE MAX( ZCODE )
  INTO GV_ZCODE
  FROM ZTTEST_215_HR.

SELECT SINGLE MIN( ZCODE )
  INTO GV_ZCODE
  FROM ZTTEST_215_HR.

DATA : LV_ZNAME2 LIKE ZTTEST_215_HR-ZNAME,
       LV_ZAGE2 LIKE ZTTEST_215_HR-ZAGE.

SELECT SINGLE ZNAME SUM( ZAGE )
  INTO ( LV_ZNAME2, LV_ZAGE2 )
  FROM ZTTEST_215_HR
  WHERE ZNAME = '216'
  GROUP BY ZNAME.

DATA : BEGIN OF GS_ZADDRESS,
        ZADDRESS LIKE ZTTEST_215_HR-ZADDRESS,
        ZAGE LIKE ZTTEST_215_HR-ZAGE,
       END OF GS_ZADDRESS.

DATA : GT_ZADDRESS LIKE TABLE OF GS_ZADDRESS.

SELECT ZADDRESS SUM( ZAGE )
  INTO TABLE GT_ZADDRESS
  FROM ZTTEST_215_HR
  WHERE ZADDRESS IN ( '서울시 종로구', '서울시 은평구' )
  GROUP BY ZADDRESS
  HAVING SUM( ZAGE ) <= 103.
*  HAVING SUM( ZAGE ) <= 70.

SELECT SINGLE ZNAME AVG( ZAGE )
  INTO ( LV_ZNAME2, LV_ZAGE2 )
  FROM ZTTEST_215_HR
  WHERE ZNAME = '216'
  GROUP BY ZNAME.

DATA : LV_COUNT TYPE I.
SELECT SINGLE ZNAME COUNT( * ) AS COUNT
  INTO ( LV_ZNAME2, LV_COUNT )
  FROM ZTTEST_215_HR
  WHERE ZNAME = '216'
  GROUP BY ZNAME.

DATA : BEGIN OF GS_ZNAME,
        ZNAME LIKE ZTTEST_215_HR-ZNAME,
       END OF GS_ZNAME.

DATA : GT_ZNAME LIKE TABLE OF GS_ZNAME.

SELECT DISTINCT ZNAME
  INTO TABLE GT_ZNAME
  FROM ZTTEST_215_HR
  WHERE ZAGE BETWEEN '20' AND '35'.

DATA : BEGIN OF GS_ZCODE,
        ZCODE LIKE ZTTEST_215_HR-ZCODE,
       END OF GS_ZCODE.

DATA : GT_ZCODE LIKE TABLE OF GS_ZCODE.

SELECT ZCODE
  INTO TABLE GT_ZCODE
  FROM ZTTEST_215_HR.

SELECT ZCODE
  INTO TABLE GT_ZCODE
  FROM ZTTEST_215_HR
  ORDER BY ZCODE.

SELECT ZCODE
  INTO TABLE GT_ZCODE
  FROM ZTTEST_215_HR
  ORDER BY ZCODE DESCENDING.



"INSERT
"UPDATE
"MODIFY
"DELETE

*INSERT DB FROM GS_DATA.
*INSERT DB FROM TABLE GT_DATA.
*
*UPDATE DB FROM GS_DATA.
*UPDATE DB FROM GT_DATA.
*
*MODIFY DB FROM GS_DATA.
*MODIFY DB FROM TABLE GT_DATA.
*
*DELETE DB FROM GS_DATA.
*DELETE DB FROM TABLE GT_DATA.
*DELETE FROM DB WHERE F1 = 조건.

"INSERT 실습! INSERT 실습! INSERT 실습! INSERT 실습! INSERT 실습!
DATA : GS_ZTTEST_215_HR_12 LIKE ZTTEST_215_HR.

*GS_ZTTEST_215_HR_12-ZCODE = '006'.
*GS_ZTTEST_215_HR_12-ZNAME = '216'.
*GS_ZTTEST_215_HR_12-ZGENDER = '여'.
*GS_ZTTEST_215_HR_12-ZPHONE = '01011112222'.
*GS_ZTTEST_215_HR_12-ZADDRESS = '서울시 종로구'.
*GS_ZTTEST_215_HR_12-ZAGE = '23'.
*GS_ZTTEST_215_HR_12-ZHOBBY = '아밥'.
*
*INSERT ZTTEST_215_HR FROM GS_ZTTEST_215_HR_12.
*INSERT ZTTEST_215_HR FROM TABLE GT_ZTTEST_215_HR_12.

SELECT SINGLE MAX( ZCODE )
  INTO GV_ZCODE
  FROM ZTTEST_215_HR.

IF GV_ZCODE IS NOT INITIAL.
  GS_ZTTEST_215_HR_12-ZCODE = GV_ZCODE + 1.
  CONDENSE GS_ZTTEST_215_HR_12-ZCODE.
  CONCATENATE '00' GS_ZTTEST_215_HR_12-ZCODE INTO GS_ZTTEST_215_HR_12-ZCODE.
  GS_ZTTEST_215_HR_12-ZNAME = '216'.
  GS_ZTTEST_215_HR_12-ZGENDER = '여'.
  GS_ZTTEST_215_HR_12-ZPHONE = '01011112222'.
  GS_ZTTEST_215_HR_12-ZADDRESS = '서울시 종로구'.
  GS_ZTTEST_215_HR_12-ZAGE = '23'.
  GS_ZTTEST_215_HR_12-ZHOBBY = '아밥'.

*  INSERT ZTTEST_215_HR FROM GS_ZTTEST_215_HR_12.
ENDIF.

DATA : GV_SNRO LIKE ZTTEST_215_HR-ZCODE.

*CLEAR GV_SNRO.
*CALL FUNCTION 'NUMBER_GET_NEXT'
*  EXPORTING
*    NR_RANGE_NR                   = '01'
*    OBJECT                        = 'ZT_ZCODE'
**     QUANTITY                      = '1'
**     SUBOBJECT                     = ' '
**     TOYEAR                        = '0000'
**     IGNORE_BUFFER                 = ' '
* IMPORTING
*   NUMBER                        = GV_SNRO
**     QUANTITY                      =
**     RETURNCODE                    =
**   EXCEPTIONS
**     INTERVAL_NOT_FOUND            = 1
**     NUMBER_RANGE_NOT_INTERN       = 2
**     OBJECT_NOT_FOUND              = 3
**     QUANTITY_IS_0                 = 4
**     QUANTITY_IS_NOT_1             = 5
**     INTERVAL_OVERFLOW             = 6
**     BUFFER_OVERFLOW               = 7
**     OTHERS                        = 8
*            .
*IF SY-SUBRC <> 0.
** Implement suitable error handling here
*ENDIF.
*
*GS_ZTTEST_215_HR_12-ZCODE = GV_SNRO.
*
*GS_ZTTEST_215_HR_12-ZNAME = '216'.
*GS_ZTTEST_215_HR_12-ZGENDER = '여'.
*GS_ZTTEST_215_HR_12-ZPHONE = '01011112222'.
*GS_ZTTEST_215_HR_12-ZADDRESS = '서울시 종로구'.
*GS_ZTTEST_215_HR_12-ZAGE = '23'.
*GS_ZTTEST_215_HR_12-ZHOBBY = '아밥'.
*
*INSERT ZTTEST_215_HR FROM GS_ZTTEST_215_HR_12.
"INSERT 실습! INSERT 실습! INSERT 실습! INSERT 실습! INSERT 실습!

"UPDATE
SELECT SINGLE *
  INTO GS_ZTTEST_215_HR_12
  FROM ZTTEST_215_HR
  WHERE ZCODE = '002'.

GS_ZTTEST_215_HR_12-ZPHONE = '11111111111'.

UPDATE ZTTEST_215_HR FROM GS_ZTTEST_215_HR_12.

UPDATE ZTTEST_215_HR SET ZPHONE = '01011112222'
                     WHERE ZCODE = '003'.

UPDATE ZTTEST_215_HR SET ZPHONE = GS_ZTTEST_215_HR_12-ZPHONE
                     WHERE ZCODE = '003'.

"MODIFY = INSERT + UPDATE
DATA : GS_ZTTEST_215_HR_13 LIKE ZTTEST_215_HR.

*GS_ZTTEST_215_HR_13-ZCODE = '008'.
*GS_ZTTEST_215_HR_13-ZNAME = '216'.
*GS_ZTTEST_215_HR_13-ZGENDER = '여'.
*GS_ZTTEST_215_HR_13-ZPHONE = '01011112222'.
*GS_ZTTEST_215_HR_13-ZADDRESS = '서울시 종로구'.
*GS_ZTTEST_215_HR_13-ZAGE = '23'.
*GS_ZTTEST_215_HR_13-ZHOBBY = '아밥'.
*
*MODIFY ZTTEST_215_HR FROM GS_ZTTEST_215_HR_13.

GS_ZTTEST_215_HR_13-ZCODE = '008'.
GS_ZTTEST_215_HR_13-ZNAME = '111'.
GS_ZTTEST_215_HR_13-ZGENDER = '여'.
GS_ZTTEST_215_HR_13-ZPHONE = '0101111111'.
GS_ZTTEST_215_HR_13-ZADDRESS = '서울시 종로구'.
GS_ZTTEST_215_HR_13-ZAGE = '11'.
GS_ZTTEST_215_HR_13-ZHOBBY = '아밥2'.

MODIFY ZTTEST_215_HR FROM GS_ZTTEST_215_HR_13.
COMMIT WORK.

DATA : GT_ZTTEST_215_HR_14 LIKE ZTTEST_215_HR OCCURS 0.
DATA : GS_ZTTEST_215_HR_14 LIKE ZTTEST_215_HR.

SELECT *
  INTO TABLE GT_ZTTEST_215_HR_14
  FROM ZTTEST_215_HR
  WHERE ( ZCODE = '002' OR    ZCODE = '003' )
  AND     ZAGE < 35.

LOOP AT GT_ZTTEST_215_HR_14 INTO GS_ZTTEST_215_HR_14.
  GS_ZTTEST_215_HR_14-ZNAME = 'MODIFY'.

  MODIFY GT_ZTTEST_215_HR_14 FROM GS_ZTTEST_215_HR_14.
ENDLOOP.

MODIFY ZTTEST_215_HR FROM TABLE GT_ZTTEST_215_HR_14.

"DELETE
DATA : GS_ZTTEST_215_HR LIKE ZTTEST_215_HR.

*GS_ZTTEST_215_HR-ZCODE = 7.
*DELETE ZTTEST_215_HR FROM GS_ZTTEST_215_HR.
DELETE FROM ZTTEST_215_HR WHERE ZCODE = 7.
